#!/usr/bin/env python3
"""
make-listing.py — generate a ready-to-paste Codefling listing pack for a plugin.

Reads the repo's manifest.json (+ .plugin-standard.json, CHANGELOG.md, README.md)
and writes CODEFLING.md: title, tagline, tags, compatibility, dependencies,
permissions/commands tables, install steps, "what's new", links, and a license
line. Screenshots and final price are left as TODO placeholders.

Usage:  python3 tools/make-listing.py [REPO_PATH]   (default: current dir)

Stdlib only.
"""
import sys, os, re, json

repo = sys.argv[1] if len(sys.argv) > 1 else "."
manifest = json.load(open(os.path.join(repo, "manifest.json"), encoding="utf-8"))

std = {}
sp = os.path.join(repo, ".plugin-standard.json")
if os.path.exists(sp):
    try: std = json.load(open(sp, encoding="utf-8"))
    except Exception: pass

name   = manifest["name"]
title  = manifest.get("title", name)
ver    = manifest.get("version", "0.0.0")
desc   = manifest.get("description", "").strip()
tags   = manifest.get("tags", [])
lic    = manifest.get("license", "GPL-3.0")
links  = manifest.get("links", {})
perms  = manifest.get("permissions", [])
cmds   = manifest.get("commands", [])
deps   = manifest.get("dependencies", [])
compat = manifest.get("compatibility", {})
frames = manifest.get("compatible_frameworks", ["oxide"])

# free vs paid: OSS licenses (free) vs the DunganSoft EULA (paid)
paid = lic.startswith("LicenseRef") or (std.get("umod") is False and not lic.startswith(("GPL", "MIT", "Apache")))
price = "Set your price (paid)" if paid else "Free"
lic_note = (
    "Sold under the DunganSoft Plugin License (proprietary, no redistribution)."
    if paid else
    f"Open-source under **{lic}** — free. (To sell on Codefling you must relicense to the "
    "DunganSoft EULA and use a private repo; an open-source license can be redistributed.)"
)

# --- README "Features" section (best-effort) ---
features = []
rp = os.path.join(repo, "README.md")
if os.path.exists(rp):
    rt = open(rp, encoding="utf-8").read()
    m = re.search(r'(?im)^#{1,3}\s*Features\s*$(.*?)(?=^\s*#{1,3}\s|\Z)', rt, re.S | re.M)
    if m:
        cur = None
        for line in m.group(1).splitlines():
            s = line.strip()
            if not s:
                continue
            if s.startswith(("- ", "* ")):
                # New bullet: flush the previous one, start collecting this one.
                if cur is not None:
                    features.append(cur)
                cur = s[2:].strip()
            elif cur is not None:
                # Wrapped continuation of the current bullet — join it back on
                # rather than dropping it (which truncated multi-line bullets).
                cur += " " + s
            else:
                # Bold-lead line with no bullet dash (alternate README style).
                mm = re.match(r'^\*\*(.+?)\.?\*\*\s*[-—]?\s*(.*)$', s)
                if mm:
                    feat = mm.group(1).strip()
                    if mm.group(2).strip():
                        feat += " — " + mm.group(2).strip()
                    cur = feat
        if cur is not None:
            features.append(cur)
features = features[:10]

# --- latest CHANGELOG entry body ---
whatsnew = ""
cp = os.path.join(repo, "CHANGELOG.md")
if os.path.exists(cp):
    ct = open(cp, encoding="utf-8").read()
    m = re.search(r'(?m)^#{2}\s.*?$(.*?)(?=^#{2}\s|\Z)', ct, re.S)
    if m:
        whatsnew = m.group(1).strip()

def md_table(rows, headers):
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join([" --- "]*len(headers)) + "|"]
    for r in rows:
        out.append("| " + " | ".join(r) + " |")
    return "\n".join(out)

oxmin = compat.get("oxide_minimum", compat.get("oxide", "2.0.0"))
oxver = compat.get("oxide_verified", "")
compat_line = f"Oxide **{oxmin}+**" + (f" (verified {oxver})" if oxver else "")
if "carbon" in [f.lower() for f in frames]:
    compat_line += " · also supports **Carbon**"

L = []
L.append(f"# {title} — Codefling listing pack")
L.append("")
L.append("> Ready-to-paste copy generated by `rust-plugin-standard/tools/make-listing.py`")
L.append("> from `manifest.json` + `CHANGELOG.md`. Paste into Codefling's editor, then add")
L.append("> the screenshots and confirm the price before publishing. Regenerate on each release.")
L.append("")
# Cover/listing banner, if the repo ships one at assets/codefling/cover.png.
if os.path.exists(os.path.join(repo, "assets", "codefling", "cover.png")):
    L.append(f"![{title}](assets/codefling/cover.png)")
    L.append("")
L.append(f"- **Title:** {title}")
L.append(f"- **Version:** {ver}")
L.append(f"- **Price:** {price}")
L.append(f"- **Tags:** {', '.join(tags) if tags else '(add tags)'}")
L.append(f"- **Compatibility:** {compat_line}")
L.append(f"- **Dependencies:** " + (", ".join(f"[{d['name']}]({d.get('url','')})" for d in deps) if deps else "None"))
L.append("")
L.append("## Description")
L.append("")
L.append(desc or "(add a description)")
if features:
    L.append("")
    L.append("## Features")
    L.append("")
    L += [f"- {f}" for f in features]
if perms:
    L.append("")
    L.append("## Permissions")
    L.append("")
    L.append(md_table([[p.get("name",""), p.get("description","")] for p in perms], ["Permission", "Description"]))
if cmds:
    L.append("")
    L.append("## Commands")
    L.append("")
    L.append(md_table([[f"`{c.get('command','')}`", f"`{c.get('arguments','') or '—'}`", c.get("description","")] for c in cmds], ["Command", "Arguments", "Description"]))
L.append("")
L.append("## Installation")
L.append("")
L.append(f"1. Download `{name}.cs` from the latest release.")
L.append(f"2. Upload it to `oxide/plugins/{name}.cs` on your server.")
L.append("3. The plugin compiles and loads automatically; a default config is written to "
         f"`oxide/config/{name}.json` on first load.")
if deps:
    L.append("4. Install the required dependencies listed above first.")
if std.get("signed"):
    L.append("")
    L.append("## Verifying the download")
    L.append("")
    L.append(f"This plugin is **code-signed**. Every release attaches a detached OpenPGP "
             f"signature (`{name}.cs.asc`) and the public key (`gjdunga.asc`):")
    L.append("")
    L.append("```bash")
    L.append("gpg --import gjdunga.asc   # fingerprint EAC0A2AE65CC6C9762DD6AF06877843761D5C6E6")
    L.append(f"gpg --verify {name}.cs.asc {name}.cs")
    L.append("```")
    L.append("")
    L.append('Expect: `Good signature from "Gabriel Dungan <gjdunga@gmail.com>"`.')
if whatsnew:
    L.append("")
    L.append(f"## What's new in {ver}")
    L.append("")
    L.append(whatsnew)
L.append("")
L.append("## Links")
L.append("")
for label, key in [("Source", "source"), ("Documentation", "documentation"), ("Issues", "issues")]:
    if links.get(key):
        L.append(f"- {label}: {links[key]}")
L.append("")
L.append("## License")
L.append("")
L.append(lic_note)
L.append("")
L.append("---")
L.append("")
L.append("**TODO before publishing:** add 2–3 screenshots (in-game UI / console output), "
         "confirm the price, and link a support channel (GitHub issues or Discord).")
L.append("")

open(os.path.join(repo, "CODEFLING.md"), "w", encoding="utf-8").write("\n".join(L))
print(f"wrote {os.path.join(repo, 'CODEFLING.md')}  ({title} v{ver}, price={price})")
